import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "inverse-surface": "#28313c",
        "surface": "#f8f9ff",
        "inverse-primary": "#a4c9ff",
        "surface-container": "#e5effd",
        "background": "#f8f9ff",
        "surface-dim": "#d2dbe9",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#633f00",
        "on-tertiary-fixed": "#291800",
        "on-secondary-fixed": "#001f24",
        "on-tertiary-container": "#ffce8e",
        "on-primary-fixed": "#001c39",
        "primary": "#004682",
        "surface-variant": "#dae3f1",
        "tertiary-fixed": "#ffddb4",
        "on-error-container": "#93000a",
        "outline-variant": "#c1c6d3",
        "on-background": "#131c26",
        "surface-tint": "#0f5faa",
        "secondary": "#006874",
        "primary-fixed": "#d4e3ff",
        "inverse-on-surface": "#e9f1ff",
        "on-surface": "#131c26",
        "secondary-fixed-dim": "#79d4e2",
        "secondary-fixed": "#95f1ff",
        "on-surface-variant": "#414751",
        "on-secondary-container": "#006f7b",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#a4c9ff",
        "tertiary": "#613e00",
        "surface-container-high": "#e0e9f7",
        "on-secondary-fixed-variant": "#004f57",
        "on-primary-container": "#c0d8ff",
        "tertiary-fixed-dim": "#ffb955",
        "error": "#ba1a1a",
        "tertiary-container": "#815300",
        "on-secondary": "#ffffff",
        "secondary-container": "#95f1ff",
        "surface-container-highest": "#dae3f1",
        "on-tertiary": "#ffffff",
        "outline": "#727782",
        "on-error": "#ffffff",
        "surface-container-low": "#eef4ff",
        "on-primary-fixed-variant": "#004884",
        "primary-container": "#0b5ea8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        margin: "3rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "code-spec": ["var(--font-inter)", "monospace"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "display-mobile": ["var(--font-plus-jakarta-sans)", "sans-serif"],
        display: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "code-spec": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
